### PR TITLE
Add Consumer Complaint Database documentation 

### PR DESCRIPTION
**Pull request by cfarm**
# Do not merge until 2/23

This PR adds the Consumer Complaint Database API documentation that currently lives at www.consumerfinance.gov/complaintdatabase/technical-documentation/ to the Open Tech site. This is part of the CCDB 4.1 project (see GHE for background: https://GHE/CCDB4/ccdb-4.1-planning/issues/12). This should not be merged until our project release date, 2/23/16.
- This has been QA across all supported browsers + bug fixes have already been made.
- Content + copy have been reviewed and this PR is being made to prepare for merge on **2/23** between 10am-12pm for the CCDB 4.1 project launch.

## Additions

- `ccdb` folder contains documentation pages for the Complaint Database API
- `nav-ccdb.html` contains CCDB specific navigation links
- new layout type, `ccdb`, to display CCDB-specific navigation include
- CSS from Capital Framework components:
  - [cf-tables](https://github.com/cfpb/cf-tables) for the small screen stacked table styling on the Field Reference page
  - [cf-expandables](https://github.com/cfpb/capital-framework/tree/canary/src/cf-expandables) for the Release notes page - fixes the styling and functionality for all supported browsers (previous JS did not work in older IE)
  - [cf-typography](https://github.com/cfpb/capital-framework/tree/canary/src/cf-typography) and [cf-icons](https://github.com/cfpb/capital-framework/tree/canary/src/cf-icons) for the expandables show/hide + PDF icons

## Removals

- old expandables JS + CSS - this does not seem to affect the [HMDA pages](https://cfarm.github.io/api-1/hmda).

## Changes

- use `kramdown` for markdown on Github pages, see https://help.github.com/articles/migrating-your-pages-site-from-maruku/ 

## Testing

- check out these changes here: 
 - https://cfarm.github.io/api-1/ccdb/
 - https://cfarm.github.io/api-1/hmda

## Review

- @ascott1 

### [Release notes](http://cfarm.github.io/api-1/ccdb/notes.html)
screen shot 2016-01-19 at 12 03 22 pm
screen shot 2016-01-19 at 12 03 13 pm

### [Field reference](http://cfarm.github.io/api-1/ccdb/fields.html)
screen shot 2016-01-19 at 12 03 40 pm
screen shot 2016-01-19 at 12 03 31 pm

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Visually tested in supported browsers and devices 
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by ascott1** [comment]
This is looking great @cfarm! :+1: from me to merge on 1/28.

**Comment by huetingj** [comment]
:tada: good job @cfarm!

**Comment by Scotchester** [comment]
Minor suggestion: rename `notes.html` to the more explicit `release-notes.html`.

**Comment by cfarm** [comment]
@Scotchester done. I also updated the cf.gov redirects file that pointed to notes.html

**Comment by Scotchester** [comment]
@cfarm Thanks! You rock :metal:

**Comment by cfarm** [comment]
## Ready for merge 2/23

Some cleared content updates for release:

* [Release notes](https://cfarm.github.io/api-1/ccdb/release-notes.html) now say February for latest release
screen shot 2016-02-17 at 6 07 05 pm

* [Field reference] for "Tags" + "Consumer consent provided?" fields. Also renamed the "Indexed?" column to "Notes"

**Comment by cfarm** [comment]
@ascott1 @Scotchester Just a reminder that we are scheduled to merge this puppy :dog2: between 11am-12pm tomorra. I will perform the delicate and complex procedure known as the 'self-merge' at that hour.

**Comment by ascott1** [comment]
:+1:

**Pull request merged**
